; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nodemcu-32s]
platform = espressif32
board = nodemcu-32s
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps = 
	https://github.com/toastmanAu/wyltek-embedded-builder.git
	https://github.com/ESP32Async/ESPAsyncWebServer
	https://github.com/ESP32Async/AsyncTCP
lib_ldf_mode = chain+
build_unflags = 
	-std=gnu++11
build_flags = 
	-std=gnu++17
	-DWY_GM861S_BUF_SIZE=1024
